### ISSUE TITLE
Nesting of todos

### ISSUE THREAD

**Issue by hkdobrev** [RStankov/FocusedTask#11]
This is a feature request to add the ability to nest todos.

- Nested todos would allow grouping of tasks together or listing subtasks as part of a bigger task.
- Nested todos could act as normal todos, but be visually indented to the right under its parent todo.
- I'd recommend up to only 1 level of nesting.
- When moving or checking parent todos, all nested todos should follow.
- In order to create nested todos: 1) A top-level todo could have a button to add a child todo 2) An existing todo could be nested.
- Nested todos could be dragged from one todo to another changing their parent.
- Keyboard shortcut for nesting/denesting a todo could be useful. Usually <kbd>Tab</kbd>, but it's currently used to cycle focus through sections.

What do you think? Would that be a feature to be considered for the app?

**Comment by hkdobrev** [comment]
Never mind, just found the shortcut for indenting and noticed the drag and drop works as well. I was confused as the tab didn't work like that.

**Comment by RStankov** [comment]
`tab` didn't work because, used to jump between todos :)
