### ISSUE TITLE
Keyboard shortcut for toggling lists

### ISSUE THREAD

**Issue by hkdobrev** [RStankov/FocusedTask#12]
Could we have a shortcut which would toggle between different lists?

The global shortcut is very useful, but if I have a personal and a work list it'd be easier if I can use just the keyboard to switch between them after using the global shortcut to show the app.

**Comment by RStankov** [comment]
I have the same issue. I still haven't figured out a good shortcut for this. I'm open to ideas?

**Comment by hkdobrev** [comment]
Use the shortcut for switching between application windows. It's Cmd + ` on macOS.

**Comment by RStankov** [comment]
I like this idea. Will implement 🙌

**Comment by RStankov** [comment]
✅ Added  and released

This was surpassingly tricky to implement 😅

Because "CMD + `" is system shortcut, I had to overwrite and restore when using the app. 

https://github.com/RStankov/FocusedTask/commit/d99e9ecb2e321ddb80ff17cd46ab3be461825ab9
