### ISSUE TITLE
heroku download link appears to be down

### ISSUE THREAD

**Issue by TJHdev** [RStankov/FocusedTask#21]
As title suggests the latest download link seems to be down, I am assuming this was an installable version of the app?

I've managed to get the dev build working and the functionality seems ideal. Good job!

Edit - Changed browser, the download link is working.

**Comment by RStankov** [comment]
In which browse was it broken?

I think, the issue is heroku need time to boot the app if not live.

**Comment by TJHdev** [comment]
It was chrome on MacOs. I don't think it's an issue with the browser more to do with it opening another window. The tab opens temporarily for me then closes without having downloaded the .zip. If I paste the link into a new tab directly it works as intended.

Just tested again. Does seem to be an issue just on chrome for me, could be a plugin I'm running though.

**Comment by TJHdev** [comment]
Awesome project btw, exactly what I was looking for! If you're open to pull requests I'm adding a couple more shortcuts. 

1. focus title 'cmd + e'
2. open shortcuts 'cmd + h' 

maybe a dark mode too?

**Comment by RStankov** [comment]
@TJHdev always happy to get contributions. Especially the dark mode :)
